[project]
name = "test_task"
version = "0.1.0"
description = "Test task for parsing aetna"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.115.12",
    "jsonlines>=4.0.0",
    "sqlalchemy>=2.0.40",
    "uvicorn>=0.34.0",
]
